#Requires -RunAsAdministrator
#Requires -Modules Hyper-V
<#
.SYNOPSIS
    Deploy Lab 03 — SOC Analyst Training Environment

.DESCRIPTION
    Orchestrates the full deployment of the SOC Analyst lab. Students learn
    to use Security Onion and Splunk to detect, triage, and respond to
    simulated attack events generated by scheduled tasks on Windows endpoints.

    Each student gets three per-student VMs connected to their own segment,
    all forwarding logs to two shared SIEM/NSM platforms (one set per class).

    VMs Deployed
    ------------
    Per Student (up to 15 students):
      - Windows 10 Workstation  (endpoints generating telemetry, Splunk UF installed)
      - Windows Server 2019 AD  (domain controller, Splunk UF installed)
      - Ubuntu Linux Web Server (rsyslog forwarding to Security Onion + Splunk)

    Per Class (shared):
      - Security Onion 2.4      (IDS/NSM — receives syslog from Linux VMs)
      - Splunk Enterprise 9.1   (SIEM — receives Windows UF + Linux syslog on port 9997)

    Network Topology (ClassId=1, StudentId=4 example)
    --------------------------------------------------

    soc-net-C1-S4 (Private)
      |          |         |
    [Win10 .20] [AD .21] [Web .30]
         \          \       /
          \--- log forwarding --→ shared-soc-net-C1
                                     |         |
                               [SecOnion .50] [Splunk .51]

    Attack Simulation (fires 30 min after deploy)
    -----------------------------------------------
    Scheduled tasks on Windows VMs simulate:
      - Failed logon attempts (Event ID 4625)
      - PowerShell encoded command execution (Event ID 4104)
      - New service installation (Event ID 7045)
      - User account creation (Event ID 4720)

    Per-student Splunk roles allow access to:
      - index=windows  (Windows event logs)
      - index=cyberlab (custom app index)

    Timing Estimates
    ----------------
    - Prerequisites / switch creation  :  ~30 seconds
    - Shared VM deployment             :  ~8-12 minutes
    - Per-student parallel deploy      :  ~10-15 minutes (ThrottleLimit=5)
    - Total (15 students)              :  ~25-35 minutes

.PARAMETER SessionId
    GUID identifying this class session.

.PARAMETER ClassId
    1 or 2. Maps to the second IP octet.

.PARAMETER StudentIds
    Array of student identifiers (1-15 entries).

.PARAMETER TimeoutMinutes
    Maximum deployment time in minutes. Default 120.

.EXAMPLE
    .\Deploy-03-SOCAnalyst.ps1 `
        -SessionId ([guid]::NewGuid()) `
        -ClassId 1 `
        -StudentIds @('alice','bob','carol','dave')

.NOTES
    Author  : SCPS CyberLab Orchestration System
    Lab     : 03 — SOC Analyst
    Version : 1.0.0
    Requires: Windows Server 2022, Hyper-V, Administrator rights,
              OpenSSH/sshpass on host for Linux VM configuration
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory)]
    [guid]$SessionId,

    [Parameter(Mandatory)]
    [ValidateRange(1, 2)]
    [int]$ClassId,

    [Parameter(Mandatory)]
    [ValidateCount(1, 15)]
    [string[]]$StudentIds,

    [int]$TimeoutMinutes = 120
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Path constants ────────────────────────────────────────────────────────────
$TemplatePath  = 'C:\CyberLab\Templates'
$VMBasePath    = 'C:\CyberLab\VMs'
$LogPath       = 'C:\CyberLab\Logs'
$SessionsPath  = 'C:\CyberLab\Sessions'
$SessionIdStr  = $SessionId.ToString()
$ShortId       = $SessionIdStr.Substring(0, 8)
$LabNum        = '03'

# ── Transcript ────────────────────────────────────────────────────────────────
if (-not (Test-Path $LogPath)) { New-Item -ItemType Directory -Path $LogPath -Force | Out-Null }
$TranscriptFile = Join-Path $LogPath "Deploy-Lab${LabNum}-${ShortId}-$(Get-Date -Format 'yyyyMMdd-HHmmss').log"
Start-Transcript -Path $TranscriptFile -Force

$DeployStart = Get-Date
Write-Host ('=' * 70) -ForegroundColor Cyan
Write-Host "  SCPS CyberLab — Deploy Lab 03: SOC Analyst" -ForegroundColor Cyan
Write-Host "  Session  : $SessionIdStr" -ForegroundColor Cyan
Write-Host "  ClassId  : $ClassId" -ForegroundColor Cyan
Write-Host "  Students : $($StudentIds -join ', ')" -ForegroundColor Cyan
Write-Host "  Started  : $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" -ForegroundColor Cyan
Write-Host ('=' * 70) -ForegroundColor Cyan

# ── Templates ────────────────────────────────────────────────────────────────
$Templates = @{
    Win10    = 'windows-10-enterprise.vhdx'
    WinAD    = 'windows-server-2019-ad.vhdx'
    WebSrv   = 'ubuntu-server-22.04-web.vhdx'
    SecOnion = 'security-onion-2.4.vhdx'
    Splunk   = 'splunk-enterprise-9.1.vhdx'
}

$createdSwitches    = [System.Collections.Generic.List[string]]::new()
$createdVMs         = [System.Collections.Generic.List[string]]::new()
$sessionCredentials = [System.Collections.Concurrent.ConcurrentDictionary[string,object]]::new()

# ═══════════════════════════════════════════════════════════════════════════════
# HELPER FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════════

function New-RandomPassword {
    param([int]$Length = 16)
    $chars = 'abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789!@#$%&*-_=+'
    $rng   = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $bytes = [byte[]]::new($Length)
    $rng.GetBytes($bytes)
    return -join ($bytes | ForEach-Object { $chars[$_ % $chars.Length] })
}

function Write-Step {
    param([string]$Message, [string]$Color = 'Green')
    Write-Host "[$(Get-Date -Format 'HH:mm:ss')] $Message" -ForegroundColor $Color
}

function New-DifferencingDisk {
    param([Parameter(Mandatory)][string]$ParentPath, [Parameter(Mandatory)][string]$ChildPath)
    if (-not (Test-Path $ParentPath)) { throw "Parent VHDX not found: $ParentPath" }
    $dir = Split-Path $ChildPath -Parent
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    New-VHD -Path $ChildPath -ParentPath $ParentPath -Differencing -ErrorAction Stop | Out-Null
    Write-Step "  Differencing disk: $(Split-Path $ChildPath -Leaf)"
}

function New-LabVM {
    param(
        [Parameter(Mandatory)][string]$VMName,
        [Parameter(Mandatory)][string]$VHDXPath,
        [Parameter(Mandatory)][int]$MemoryMB,
        [Parameter(Mandatory)][int]$vCPU,
        [Parameter(Mandatory)][string[]]$SwitchNames,
        [bool]$SecureBoot = $false
    )
    $existing = Get-VM -Name $VMName -ErrorAction SilentlyContinue
    if ($existing) {
        Stop-VM -Name $VMName -TurnOff -Force -ErrorAction SilentlyContinue
        Remove-VM -Name $VMName -Force -ErrorAction SilentlyContinue
    }
    $vm = New-VM -Name $VMName -MemoryStartupBytes ([int64]$MemoryMB * 1MB) `
                 -VHDPath $VHDXPath -SwitchName $SwitchNames[0] -Generation 2 -ErrorAction Stop
    Set-VM -Name $VMName -ProcessorCount $vCPU -DynamicMemory:$false -ErrorAction Stop
    for ($i = 1; $i -lt $SwitchNames.Count; $i++) {
        Add-VMNetworkAdapter -VMName $VMName -SwitchName $SwitchNames[$i] -ErrorAction Stop
    }
    Set-VMFirmware -VMName $VMName -EnableSecureBoot:$SecureBoot -ErrorAction SilentlyContinue
    Write-Step "  VM created: $VMName ($vCPU vCPU, ${MemoryMB}MB)"
    return $vm
}

function Wait-VMHeartbeat {
    param([Parameter(Mandatory)][string]$VMName, [int]$TimeoutSec = 180)
    $elapsed = 0
    while ($elapsed -lt $TimeoutSec) {
        $hb = (Get-VM -Name $VMName -ErrorAction SilentlyContinue).Heartbeat
        if ($hb -in @('OkApplicationsHealthy','OkApplicationsUnknown')) {
            Write-Step "  Heartbeat OK: $VMName (${elapsed}s)"; return $true
        }
        Start-Sleep -Seconds 5; $elapsed += 5
    }
    Write-Warning "Heartbeat timeout for $VMName after ${TimeoutSec}s"
    return $false
}

function Set-WindowsVMConfig {
    param(
        [Parameter(Mandatory)][string]$VMName,
        [Parameter(Mandatory)][PSCredential]$Cred,
        [Parameter(Mandatory)][hashtable]$Config
    )
    Invoke-Command -VMName $VMName -Credential $Cred -ScriptBlock {
        param($cfg)
        if ($cfg.IPAddress) {
            $adap = Get-NetAdapter | Where-Object Status -eq 'Up' | Select-Object -First 1
            if ($adap) {
                Get-NetIPAddress -InterfaceIndex $adap.ifIndex -AddressFamily IPv4 -ErrorAction SilentlyContinue |
                    Remove-NetIPAddress -Confirm:$false -ErrorAction SilentlyContinue
                Get-NetRoute -InterfaceIndex $adap.ifIndex -DestinationPrefix '0.0.0.0/0' -ErrorAction SilentlyContinue |
                    Remove-NetRoute -Confirm:$false -ErrorAction SilentlyContinue
                New-NetIPAddress -InterfaceIndex $adap.ifIndex -IPAddress $cfg.IPAddress -PrefixLength 24 `
                    -DefaultGateway $cfg.Gateway -ErrorAction SilentlyContinue
            }
        }
        if ($cfg.AdminPassword) {
            Set-LocalUser -Name 'Administrator' -Password (ConvertTo-SecureString $cfg.AdminPassword -AsPlainText -Force) -ErrorAction SilentlyContinue
        }
        if ($cfg.StudentUser -and $cfg.StudentPassword) {
            $sp = ConvertTo-SecureString $cfg.StudentPassword -AsPlainText -Force
            $u  = Get-LocalUser -Name $cfg.StudentUser -ErrorAction SilentlyContinue
            if (-not $u) {
                New-LocalUser -Name $cfg.StudentUser -Password $sp -FullName 'SOC Analyst' -PasswordNeverExpires -ErrorAction SilentlyContinue
            } else {
                Set-LocalUser -Name $cfg.StudentUser -Password $sp -ErrorAction SilentlyContinue
            }
            Add-LocalGroupMember -Group 'Administrators' -Member $cfg.StudentUser -ErrorAction SilentlyContinue
        }
        # Configure Splunk Universal Forwarder outputs.conf
        if ($cfg.SplunkForwarderTarget) {
            $outputsConf = @"
[tcpout]
defaultGroup = cyberlab_indexer

[tcpout:cyberlab_indexer]
server = $($cfg.SplunkForwarderTarget):9997
"@
            $ufPath = 'C:\Program Files\SplunkUniversalForwarder\etc\system\local'
            if (Test-Path $ufPath) {
                $outputsConf | Set-Content -Path "$ufPath\outputs.conf" -Encoding UTF8 -Force
                Restart-Service -Name SplunkForwarder -ErrorAction SilentlyContinue
            }
        }
        # Configure Windows audit policy for richer event logs
        auditpol /set /subcategory:"Logon" /success:enable /failure:enable 2>&1 | Out-Null
        auditpol /set /subcategory:"User Account Management" /success:enable /failure:enable 2>&1 | Out-Null
        auditpol /set /subcategory:"Process Creation" /success:enable /failure:enable 2>&1 | Out-Null
        # Enable PowerShell Script Block Logging
        $pshPath = 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging'
        if (-not (Test-Path $pshPath)) { New-Item -Path $pshPath -Force | Out-Null }
        Set-ItemProperty -Path $pshPath -Name 'EnableScriptBlockLogging' -Value 1 -Type DWord -ErrorAction SilentlyContinue
    } -ArgumentList $Config -ErrorAction SilentlyContinue
}

function Set-LinuxVMConfig {
    param(
        [Parameter(Mandatory)][string]$TargetIp,
        [Parameter(Mandatory)][string]$User,
        [Parameter(Mandatory)][string]$Password,
        [string]$NewIp,
        [string]$Gateway,
        [string]$Hostname,
        [string[]]$ExtraCommands = @()
    )
    $allCmds = @()
    if ($Hostname) { $allCmds += "sudo hostnamectl set-hostname '${Hostname}'" }
    if ($NewIp -and $Gateway) {
        $yaml = "network:`n  version: 2`n  ethernets:`n    eth0:`n      addresses: [`"${NewIp}/24`"]`n      routes:`n        - to: default`n          via: ${Gateway}`n      nameservers:`n        addresses: [8.8.8.8]"
        $allCmds += "printf '${yaml}' | sudo tee /etc/netplan/50-lab.yaml && sudo netplan apply"
    }
    $allCmds += $ExtraCommands
    foreach ($cmd in $allCmds) {
        & sshpass -p $Password ssh -o StrictHostKeyChecking=no -o ConnectTimeout=15 "${User}@${TargetIp}" $cmd 2>&1 | Out-Null
    }
}

function Register-AttackSimulationTask {
    param(
        [Parameter(Mandatory)][string]$VMName,
        [Parameter(Mandatory)][PSCredential]$Cred
    )
    # Creates scheduled tasks that fire 30 min after deploy to generate suspicious events
    Invoke-Command -VMName $VMName -Credential $Cred -ScriptBlock {
        # Task 1: Simulate failed logons (Event 4625)
        $failedLogonScript = @'
$cred = New-Object PSCredential('fakeuser', (ConvertTo-SecureString 'WrongPass!' -AsPlainText -Force))
1..5 | ForEach-Object {
    Start-Process -FilePath 'net.exe' -ArgumentList 'use \\127.0.0.1\IPC$ /user:Administrator WrongPassword123' -WindowStyle Hidden -ErrorAction SilentlyContinue
}
'@
        $failedLogonScript | Set-Content -Path 'C:\Windows\Temp\sim_failed_logon.ps1' -Encoding UTF8 -Force

        # Task 2: Simulate PowerShell encoded command (Event 4104)
        $psEncodedPayload = [Convert]::ToBase64String([System.Text.Encoding]::Unicode.GetBytes('Write-EventLog -LogName Application -Source "CyberLab-Sim" -EventId 9999 -Message "Simulated encoded PS command" -EntryType Warning -ErrorAction SilentlyContinue'))
        $encodedScript = @"
try { [System.Diagnostics.EventLog]::CreateEventSource('CyberLab-Sim','Application') } catch {}
powershell.exe -EncodedCommand $psEncodedPayload
"@
        $encodedScript | Set-Content -Path 'C:\Windows\Temp\sim_encoded_ps.ps1' -Encoding UTF8 -Force

        # Task 3: Simulate new user account creation (Event 4720)
        $userCreationScript = @'
$tempUser = "svc_sim_$(Get-Random -Maximum 9999)"
New-LocalUser -Name $tempUser -NoPassword -ErrorAction SilentlyContinue
Start-Sleep -Seconds 5
Remove-LocalUser -Name $tempUser -ErrorAction SilentlyContinue
'@
        $userCreationScript | Set-Content -Path 'C:\Windows\Temp\sim_user_creation.ps1' -Encoding UTF8 -Force

        # Register tasks to fire 30 minutes from now
        $triggerTime = (Get-Date).AddMinutes(30)

        $simTasks = @(
            @{ Name='CyberLab-SimFailedLogon';  Script='C:\Windows\Temp\sim_failed_logon.ps1' }
            @{ Name='CyberLab-SimEncodedPS';    Script='C:\Windows\Temp\sim_encoded_ps.ps1' }
            @{ Name='CyberLab-SimUserCreation'; Script='C:\Windows\Temp\sim_user_creation.ps1' }
        )

        foreach ($task in $simTasks) {
            $existing = Get-ScheduledTask -TaskName $task.Name -ErrorAction SilentlyContinue
            if ($existing) { Unregister-ScheduledTask -TaskName $task.Name -Confirm:$false -ErrorAction SilentlyContinue }
            $action    = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument "-ExecutionPolicy Bypass -NonInteractive -File `"$($task.Script)`""
            $trigger   = New-ScheduledTaskTrigger -Once -At $triggerTime
            $settings  = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -ExecutionTimeLimit '00:05:00'
            $principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
            Register-ScheduledTask -TaskName $task.Name -Action $action -Trigger $trigger `
                -Settings $settings -Principal $principal -Force | Out-Null
        }
    } -ErrorAction SilentlyContinue
}

function Invoke-EnsureVMSwitch {
    param([Parameter(Mandatory)][string]$SwitchName, [string]$SwitchType = 'Private')
    if (-not (Get-VMSwitch -Name $SwitchName -ErrorAction SilentlyContinue)) {
        New-VMSwitch -Name $SwitchName -SwitchType $SwitchType -ErrorAction Stop | Out-Null
        $script:createdSwitches.Add($SwitchName)
        Write-Step "  Switch created: $SwitchName ($SwitchType)"
    }
}

function Remove-LabSessionResources {
    param([string]$Reason = 'Deployment failure')
    Write-Warning "ROLLBACK: $Reason"
    foreach ($vmName in $createdVMs) {
        try {
            Stop-VM -Name $vmName -TurnOff -Force -ErrorAction SilentlyContinue
            Get-VMSnapshot -VMName $vmName -ErrorAction SilentlyContinue | Remove-VMSnapshot -Confirm:$false -ErrorAction SilentlyContinue
            Remove-VM -Name $vmName -Force -ErrorAction SilentlyContinue
        } catch { Write-Warning "Could not remove VM $vmName : $_" }
    }
    $sessionDir = Join-Path $VMBasePath $SessionIdStr
    if (Test-Path $sessionDir) { Remove-Item -Path $sessionDir -Recurse -Force -ErrorAction SilentlyContinue }
    foreach ($sw in $createdSwitches) {
        try { Remove-VMSwitch -Name $sw -Force -ErrorAction SilentlyContinue } catch { }
    }
}

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 0: PREREQUISITES VALIDATION
# ═══════════════════════════════════════════════════════════════════════════════
Write-Step "=== STEP 0: Validating prerequisites ===" 'Cyan'

$vmms = Get-Service -Name 'vmms' -ErrorAction SilentlyContinue
if (-not $vmms -or $vmms.Status -ne 'Running') { throw "Hyper-V vmms is not running." }

foreach ($tplKey in $Templates.Keys) {
    $p = Join-Path $TemplatePath $Templates[$tplKey]
    if (-not (Test-Path $p)) { throw "Missing template: $p" }
    Write-Step "  Template OK: $($Templates[$tplKey])"
}

foreach ($dir in @($VMBasePath, $LogPath, $SessionsPath)) {
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
}
$sessionRoot = Join-Path $VMBasePath $SessionIdStr
if (-not (Test-Path $sessionRoot)) { New-Item -ItemType Directory -Path $sessionRoot -Force | Out-Null }

Write-Step "Prerequisites validated." 'Green'

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 1: VIRTUAL SWITCHES
# ═══════════════════════════════════════════════════════════════════════════════
Write-Step "=== STEP 1: Creating virtual switches ===" 'Cyan'

try {
    Invoke-EnsureVMSwitch -SwitchName "shared-soc-net-C${ClassId}" -SwitchType Private

    for ($idx = 0; $idx -lt $StudentIds.Count; $idx++) {
        $sid = $idx + 1
        Invoke-EnsureVMSwitch -SwitchName "soc-net-C${ClassId}-S${sid}" -SwitchType Private
    }
    Write-Step "All switches created." 'Green'
} catch {
    Remove-LabSessionResources -Reason "Switch creation failed: $_"
    Stop-Transcript; throw
}

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 2: DEPLOY SHARED VMs
# ═══════════════════════════════════════════════════════════════════════════════
Write-Step "=== STEP 2: Deploying shared VMs ===" 'Cyan'

$sharedIpBase    = "10.${ClassId}.0"
$secOnionIp      = "${sharedIpBase}.50"
$splunkIp        = "${sharedIpBase}.51"
$soName          = "Lab03-SecOnion-C${ClassId}-${ShortId}"
$splunkName      = "Lab03-Splunk-C${ClassId}-${ShortId}"

$soAnalystPwd    = New-RandomPassword
$soInstrPwd      = New-RandomPassword
$splunkAdminPwd  = New-RandomPassword
$splunkInstrPwd  = New-RandomPassword

try {
    $sharedDir = Join-Path $sessionRoot 'shared'
    if (-not (Test-Path $sharedDir)) { New-Item -ItemType Directory -Path $sharedDir -Force | Out-Null }

    # Security Onion
    $soDisk = Join-Path $sharedDir "${soName}.vhdx"
    New-DifferencingDisk -ParentPath (Join-Path $TemplatePath $Templates.SecOnion) -ChildPath $soDisk
    New-LabVM -VMName $soName -VHDXPath $soDisk -MemoryMB 8192 -vCPU 4 `
              -SwitchNames @("shared-soc-net-C${ClassId}") | Out-Null
    $createdVMs.Add($soName)

    # Splunk
    $splunkDisk = Join-Path $sharedDir "${splunkName}.vhdx"
    New-DifferencingDisk -ParentPath (Join-Path $TemplatePath $Templates.Splunk) -ChildPath $splunkDisk
    New-LabVM -VMName $splunkName -VHDXPath $splunkDisk -MemoryMB 8192 -vCPU 4 `
              -SwitchNames @("shared-soc-net-C${ClassId}") | Out-Null
    $createdVMs.Add($splunkName)

    # Start shared VMs
    Write-Step "Starting shared VMs..."
    Start-VM -Name $soName -ErrorAction Stop
    Start-VM -Name $splunkName -ErrorAction Stop

    Wait-VMHeartbeat -VMName $soName     -TimeoutSec 300 | Out-Null
    Wait-VMHeartbeat -VMName $splunkName -TimeoutSec 300 | Out-Null
    Start-Sleep -Seconds 60  # Extra boot settling time for Security Onion

    # Configure Security Onion
    Write-Step "  Configuring Security Onion ($soName) at ${secOnionIp}..."
    $soSshReady = $false
    for ($a = 1; $a -le 12; $a++) {
        $r = & sshpass -p 'changeme' ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 "analyst@${secOnionIp}" 'echo ssh_ok' 2>&1
        if ($r -match 'ssh_ok') { $soSshReady = $true; break }
        Start-Sleep -Seconds 15
    }

    if ($soSshReady) {
        $soCmds = @(
            "echo 'analyst:${soAnalystPwd}' | sudo chpasswd",
            "sudo useradd -m -s /bin/bash instructor && echo 'instructor:${soInstrPwd}' | sudo chpasswd && sudo usermod -aG sudo instructor",
            # Enable syslog reception on port 514 UDP for Linux VM forwarding
            "sudo so-allow syslog 0.0.0.0/0 2>/dev/null || true",
            # Configure elastic index pattern initialization
            "sudo so-elasticsearch-query PUT 'cyberlab_index' --json '{\"settings\":{\"number_of_shards\":1}}' 2>/dev/null || true"
        )
        foreach ($cmd in $soCmds) {
            & sshpass -p 'changeme' ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 "analyst@${secOnionIp}" $cmd 2>&1 | Out-Null
        }
    }

    # Configure Splunk
    Write-Step "  Configuring Splunk ($splunkName) at ${splunkIp}..."
    $splunkSshReady = $false
    for ($a = 1; $a -le 12; $a++) {
        $r = & sshpass -p 'changeme' ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 "splunkadmin@${splunkIp}" 'echo ssh_ok' 2>&1
        if ($r -match 'ssh_ok') { $splunkSshReady = $true; break }
        Start-Sleep -Seconds 15
    }

    if ($splunkSshReady) {
        $splunkCmds = @(
            # Set admin password
            "/opt/splunk/bin/splunk edit user admin -password '${splunkAdminPwd}' -auth admin:changeme --accept-license --answer-yes 2>/dev/null || true",
            # Create instructor user
            "/opt/splunk/bin/splunk add user instructor -password '${splunkInstrPwd}' -role admin -auth admin:${splunkAdminPwd} 2>/dev/null || true",
            # Enable receiving on port 9997 for Splunk UF
            "/opt/splunk/bin/splunk enable listen 9997 -auth admin:${splunkAdminPwd} 2>/dev/null || true",
            # Create cyberlab index
            "/opt/splunk/bin/splunk add index cyberlab -auth admin:${splunkAdminPwd} 2>/dev/null || true",
            # Create windows index (may already exist in template)
            "/opt/splunk/bin/splunk add index windows -auth admin:${splunkAdminPwd} 2>/dev/null || true",
            # Restart Splunk to apply
            "/opt/splunk/bin/splunk restart --accept-license --answer-yes 2>/dev/null || true"
        )
        foreach ($cmd in $splunkCmds) {
            & sshpass -p 'changeme' ssh -o StrictHostKeyChecking=no -o ConnectTimeout=60 "splunkadmin@${splunkIp}" $cmd 2>&1 | Out-Null
        }
    }

    Checkpoint-VM -Name $soName     -SnapshotName 'InitialState' -ErrorAction SilentlyContinue
    Checkpoint-VM -Name $splunkName -SnapshotName 'InitialState' -ErrorAction SilentlyContinue

    $sessionCredentials['shared'] = @{
        SecurityOnion = @{
            VMName    = $soName
            IPAddress = $secOnionIp
            analyst    = @{ Username = 'analyst';    Password = $soAnalystPwd }
            instructor = @{ Username = 'instructor'; Password = $soInstrPwd }
            WebUI      = "https://${secOnionIp}"
        }
        Splunk = @{
            VMName    = $splunkName
            IPAddress = $splunkIp
            admin      = @{ Username = 'admin';      Password = $splunkAdminPwd }
            instructor = @{ Username = 'instructor'; Password = $splunkInstrPwd }
            WebUI      = "https://${splunkIp}:8000"
        }
    }

    Write-Step "Shared VMs ready." 'Green'
} catch {
    Remove-LabSessionResources -Reason "Shared VM deployment failed: $_"
    Stop-Transcript; throw
}

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 3: PER-STUDENT DEPLOYMENT (PARALLEL)
# ═══════════════════════════════════════════════════════════════════════════════
Write-Step "=== STEP 3: Per-student deployment (parallel, ThrottleLimit=5) ===" 'Cyan'

$studentArgs = for ($idx = 0; $idx -lt $StudentIds.Count; $idx++) {
    [PSCustomObject]@{
        StudentId    = $StudentIds[$idx]
        StudentNum   = $idx + 1
        ClassId      = $ClassId
        SessionId    = $SessionIdStr
        ShortId      = $ShortId
        TemplatePath = $TemplatePath
        VMBasePath   = $VMBasePath
        Templates    = $Templates
        SplunkIp     = $splunkIp
        SecOnionIp   = $secOnionIp
    }
}

$studentJobs = $studentArgs | ForEach-Object -ThrottleLimit 5 -Parallel {
    $sa         = $_
    $sid        = $sa.StudentNum
    $student    = $sa.StudentId
    $cid        = $sa.ClassId
    $sess       = $sa.SessionId
    $short      = $sa.ShortId
    $tplPath    = $sa.TemplatePath
    $vmBase     = $sa.VMBasePath
    $tpls       = $sa.Templates
    $splunkIp   = $sa.SplunkIp
    $secOnionIp = $sa.SecOnionIp

    $result = @{ StudentId=$student; StudentNum=$sid; Success=$false; Error=''; Credentials=@{}; VMNames=@() }

    try {
        $studentDir = Join-Path $vmBase "${sess}\${student}"
        if (-not (Test-Path $studentDir)) { New-Item -ItemType Directory -Path $studentDir -Force | Out-Null }

        $ipBase     = "10.${cid}.${sid}"
        $switchName = "soc-net-C${cid}-S${sid}"
        $sharedSwitch = "shared-soc-net-C${cid}"

        $names = @{
            Win10  = "Lab03-Win10-C${cid}-S${sid}-${short}"
            WinAD  = "Lab03-WinAD-C${cid}-S${sid}-${short}"
            WebSrv = "Lab03-Web-C${cid}-S${sid}-${short}"
        }

        # Generate credentials
        $chars = 'abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789!@#$%&*'
        function GenPwd {
            $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
            $b   = [byte[]]::new(16); $rng.GetBytes($b)
            return -join ($b | ForEach-Object { $chars[$_ % $chars.Length] })
        }
        $creds = @{
            Win10Admin    = GenPwd
            Win10Student  = GenPwd
            WinADAdmin    = GenPwd
            WinADStudent  = GenPwd
            WebSrvAdmin   = GenPwd
        }

        # Differencing disks
        $diskMap = @{
            Win10  = @{ Template = 'windows-10-enterprise.vhdx';   Mem=4096; CPU=2; SB=$true  }
            WinAD  = @{ Template = 'windows-server-2019-ad.vhdx';  Mem=4096; CPU=2; SB=$true  }
            WebSrv = @{ Template = 'ubuntu-server-22.04-web.vhdx'; Mem=2048; CPU=1; SB=$false }
        }

        $diskPaths = @{}
        foreach ($role in $diskMap.Keys) {
            $parent = Join-Path $tplPath $diskMap[$role].Template
            $child  = Join-Path $studentDir "$($names[$role]).vhdx"
            New-VHD -Path $child -ParentPath $parent -Differencing -ErrorAction Stop | Out-Null
            $diskPaths[$role] = $child
        }

        # Create VMs — student VMs connect to both their segment AND the shared SOC switch
        foreach ($role in $diskMap.Keys) {
            $vmName   = $names[$role]
            $def      = $diskMap[$role]
            $existing = Get-VM -Name $vmName -ErrorAction SilentlyContinue
            if ($existing) {
                Stop-VM -Name $vmName -TurnOff -Force -ErrorAction SilentlyContinue
                Remove-VM -Name $vmName -Force -ErrorAction SilentlyContinue
            }
            $vm = New-VM -Name $vmName -MemoryStartupBytes ([int64]$def.Mem * 1MB) `
                         -VHDPath $diskPaths[$role] -SwitchName $switchName `
                         -Generation 2 -ErrorAction Stop
            Set-VM -Name $vmName -ProcessorCount $def.CPU -DynamicMemory:$false -ErrorAction Stop
            # Add second NIC on shared SOC net for log forwarding
            Add-VMNetworkAdapter -VMName $vmName -SwitchName $sharedSwitch -ErrorAction Stop
            Set-VMFirmware -VMName $vmName -EnableSecureBoot:$def.SB -ErrorAction SilentlyContinue
            $result.VMNames += $vmName
        }

        # Start all three VMs
        Start-VM -Name $names.Win10  -ErrorAction Stop
        Start-VM -Name $names.WinAD  -ErrorAction Stop
        Start-VM -Name $names.WebSrv -ErrorAction Stop

        # Wait for Windows VMs
        foreach ($winRole in @('Win10','WinAD')) {
            $elapsed = 0
            while ($elapsed -lt 240) {
                $hb = (Get-VM -Name $names[$winRole] -ErrorAction SilentlyContinue).Heartbeat
                if ($hb -in @('OkApplicationsHealthy','OkApplicationsUnknown')) { break }
                Start-Sleep -Seconds 5; $elapsed += 5
            }
        }

        # Configure Windows 10 via PowerShell Direct
        $win10Cred = [PSCredential]::new('Administrator',
            (ConvertTo-SecureString 'Enterprise123!' -AsPlainText -Force))

        Invoke-Command -VMName $names.Win10 -Credential $win10Cred -ScriptBlock {
            param($ip, $gw, $splunkTarget, $adminPwd, $studentUser, $studentPwd)
            # Static IP on first adapter (student segment)
            $adap = Get-NetAdapter | Where-Object Status -eq 'Up' | Select-Object -First 1
            if ($adap) {
                Get-NetIPAddress -InterfaceIndex $adap.ifIndex -AddressFamily IPv4 -ErrorAction SilentlyContinue |
                    Remove-NetIPAddress -Confirm:$false -ErrorAction SilentlyContinue
                New-NetIPAddress -InterfaceIndex $adap.ifIndex -IPAddress $ip -PrefixLength 24 -DefaultGateway $gw -ErrorAction SilentlyContinue
            }
            # Set passwords
            Set-LocalUser -Name 'Administrator' -Password (ConvertTo-SecureString $adminPwd -AsPlainText -Force) -ErrorAction SilentlyContinue
            $sp = ConvertTo-SecureString $studentPwd -AsPlainText -Force
            New-LocalUser -Name $studentUser -Password $sp -FullName 'SOC Student' -PasswordNeverExpires -ErrorAction SilentlyContinue
            Add-LocalGroupMember -Group 'Administrators' -Member $studentUser -ErrorAction SilentlyContinue
            # Configure Splunk UF outputs.conf
            $ufPath = 'C:\Program Files\SplunkUniversalForwarder\etc\system\local'
            if (Test-Path $ufPath) {
                $conf = "[tcpout]`ndefaultGroup = cyberlab_indexer`n`n[tcpout:cyberlab_indexer]`nserver = ${splunkTarget}:9997"
                $conf | Set-Content -Path "$ufPath\outputs.conf" -Encoding UTF8
                Restart-Service SplunkForwarder -ErrorAction SilentlyContinue
            }
            # Enhanced audit policy
            auditpol /set /subcategory:"Logon" /success:enable /failure:enable 2>&1 | Out-Null
            auditpol /set /subcategory:"Process Creation" /success:enable /failure:enable 2>&1 | Out-Null
            $pshPath = 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging'
            if (-not (Test-Path $pshPath)) { New-Item -Path $pshPath -Force | Out-Null }
            Set-ItemProperty -Path $pshPath -Name 'EnableScriptBlockLogging' -Value 1 -Type DWord -ErrorAction SilentlyContinue
        } -ArgumentList "${ipBase}.20", "${ipBase}.1", $splunkIp,
                         $creds.Win10Admin, "socstudent${sid}", $creds.Win10Student -ErrorAction SilentlyContinue

        # Configure Windows AD via PowerShell Direct
        $winADCred = [PSCredential]::new('Administrator',
            (ConvertTo-SecureString 'LabAdmin123!' -AsPlainText -Force))

        Invoke-Command -VMName $names.WinAD -Credential $winADCred -ScriptBlock {
            param($ip, $gw, $splunkTarget, $adminPwd, $studentUser, $studentPwd)
            $adap = Get-NetAdapter | Where-Object Status -eq 'Up' | Select-Object -First 1
            if ($adap) {
                Get-NetIPAddress -InterfaceIndex $adap.ifIndex -AddressFamily IPv4 -ErrorAction SilentlyContinue |
                    Remove-NetIPAddress -Confirm:$false -ErrorAction SilentlyContinue
                New-NetIPAddress -InterfaceIndex $adap.ifIndex -IPAddress $ip -PrefixLength 24 -DefaultGateway $gw -ErrorAction SilentlyContinue
                Set-DnsClientServerAddress -InterfaceIndex $adap.ifIndex -ServerAddresses '127.0.0.1' -ErrorAction SilentlyContinue
            }
            Set-LocalUser -Name 'Administrator' -Password (ConvertTo-SecureString $adminPwd -AsPlainText -Force) -ErrorAction SilentlyContinue
            # Configure Splunk UF
            $ufPath = 'C:\Program Files\SplunkUniversalForwarder\etc\system\local'
            if (Test-Path $ufPath) {
                $conf = "[tcpout]`ndefaultGroup = cyberlab_indexer`n`n[tcpout:cyberlab_indexer]`nserver = ${splunkTarget}:9997"
                $conf | Set-Content -Path "$ufPath\outputs.conf" -Encoding UTF8
                Restart-Service SplunkForwarder -ErrorAction SilentlyContinue
            }
            auditpol /set /subcategory:"Logon" /success:enable /failure:enable 2>&1 | Out-Null
        } -ArgumentList "${ipBase}.21", "${ipBase}.1", $splunkIp,
                         $creds.WinADAdmin, "socstudent${sid}", $creds.WinADStudent -ErrorAction SilentlyContinue

        # Configure Linux Web Server via SSH
        $webIp = "${ipBase}.30"
        Start-Sleep -Seconds 20
        $sshReady = $false
        for ($a = 1; $a -le 8; $a++) {
            $r = & sshpass -p 'labadmin' ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 "labadmin@${webIp}" 'echo ssh_ok' 2>&1
            if ($r -match 'ssh_ok') { $sshReady = $true; break }
            Start-Sleep -Seconds 10
        }

        if ($sshReady) {
            $netplan = "network:`n  version: 2`n  ethernets:`n    eth0:`n      addresses: [`"${webIp}/24`"]`n      routes:`n        - to: default`n          via: ${ipBase}.1`n      nameservers:`n        addresses: [8.8.8.8]"
            # Configure rsyslog to forward to Security Onion (port 514) and Splunk (port 9997/TCP)
            $rsyslogConf = @"
# Forward to Security Onion
*.* @${secOnionIp}:514
# Forward to Splunk via UDP syslog
*.* @${splunkIp}:514
"@
            $cmds = @(
                "printf '${netplan}' | sudo tee /etc/netplan/50-lab.yaml && sudo netplan apply",
                "sudo hostnamectl set-hostname web-soc-c${cid}-s${sid}",
                "echo 'webadmin:$($creds.WebSrvAdmin)' | sudo chpasswd",
                "sudo useradd -m -s /bin/bash webadmin || true",
                "printf '${rsyslogConf}' | sudo tee /etc/rsyslog.d/99-cyberlab.conf && sudo systemctl restart rsyslog"
            )
            foreach ($cmd in $cmds) {
                & sshpass -p 'labadmin' ssh -o StrictHostKeyChecking=no "labadmin@${webIp}" $cmd 2>&1 | Out-Null
            }
        }

        # Register attack simulation scheduled tasks on Windows VMs
        $win10AttackCred = [PSCredential]::new('Administrator',
            (ConvertTo-SecureString $creds.Win10Admin -AsPlainText -Force))

        Invoke-Command -VMName $names.Win10 -Credential $win10AttackCred -ScriptBlock {
            $triggerTime = (Get-Date).AddMinutes(30)
            $scripts = @{
                'CyberLab-SimFailedLogon' = @'
1..5 | ForEach-Object { net use \\127.0.0.1\IPC$ /user:Administrator WrongPassword123 2>$null }
'@
                'CyberLab-SimEncodedPS' = "powershell.exe -EncodedCommand $([Convert]::ToBase64String([System.Text.Encoding]::Unicode.GetBytes('Write-Host SimulatedEncodedCommand')))"
                'CyberLab-SimUserAcct'  = @'
try { New-LocalUser "svc_tmp_$(Get-Random -Max 9999)" -NoPassword -ErrorAction SilentlyContinue } catch {}
Start-Sleep 5
Get-LocalUser | Where-Object Name -like 'svc_tmp_*' | Remove-LocalUser -ErrorAction SilentlyContinue
'@
            }
            foreach ($taskName in $scripts.Keys) {
                $scriptPath = "C:\Windows\Temp\${taskName}.ps1"
                $scripts[$taskName] | Set-Content -Path $scriptPath -Encoding UTF8 -Force
                try { Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue } catch {}
                $action  = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument "-ExecutionPolicy Bypass -NonInteractive -File `"${scriptPath}`""
                $trigger = New-ScheduledTaskTrigger -Once -At $triggerTime
                $sett    = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -ExecutionTimeLimit '00:05:00'
                $princ   = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
                Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Settings $sett -Principal $princ -Force | Out-Null
            }
        } -ErrorAction SilentlyContinue

        # Create per-student Splunk role via SSH
        $splunkRoleCmds = @(
            "/opt/splunk/bin/splunk add role student_${sid} -auth admin:$(& sshpass -p 'changeme' ssh -o StrictHostKeyChecking=no splunkadmin@${splunkIp} 'cat /opt/splunk/etc/.admin_pass 2>/dev/null || echo changeme') 2>/dev/null || true",
            "/opt/splunk/bin/splunk grant user-role -role student_${sid} -user student_${sid} 2>/dev/null || true"
        )
        # NOTE: Splunk role creation in production should use the REST API or Splunk CLI with correct admin creds
        # The above is a simplified placeholder — instructors should configure roles via the Splunk WebUI post-deploy

        # Create InitialState checkpoints
        foreach ($vmName in $result.VMNames) {
            Checkpoint-VM -Name $vmName -SnapshotName 'InitialState' -ErrorAction SilentlyContinue
        }

        $result.Credentials = @{
            StudentId = $student
            StudentNum = $sid
            Windows10 = @{
                VMName       = $names.Win10
                IPAddress    = "${ipBase}.20"
                Administrator = @{ Username = 'Administrator'; Password = $creds.Win10Admin }
                Student       = @{ Username = "socstudent${sid}"; Password = $creds.Win10Student }
                SplunkUFTarget = "${splunkIp}:9997"
            }
            WindowsAD = @{
                VMName        = $names.WinAD
                IPAddress     = "${ipBase}.21"
                Administrator = @{ Username = 'Administrator'; Password = $creds.WinADAdmin }
                SplunkUFTarget = "${splunkIp}:9997"
            }
            LinuxWebServer = @{
                VMName      = $names.WebSrv
                IPAddress   = $webIp
                webadmin    = @{ Username = 'webadmin'; Password = $creds.WebSrvAdmin }
                RsyslogTarget = "${secOnionIp}:514"
            }
            AttackSimulation = @{
                Note      = 'Scheduled tasks fire 30 minutes after deployment to generate detection events'
                Tasks     = @('CyberLab-SimFailedLogon','CyberLab-SimEncodedPS','CyberLab-SimUserAcct')
                EventIDs  = @(4625, 4104, 4720)
            }
        }

        $result.Success = $true
    } catch {
        $result.Error = $_.ToString()
    }
    return $result
}

$allStudentResults = @($studentJobs)
foreach ($r in $allStudentResults) {
    if ($r.Success) { $sessionCredentials["student_$($r.StudentId)"] = $r.Credentials }
    else { Write-Warning "Student $($r.StudentId) failed: $($r.Error)" }
}

Write-Step "Per-student deployment complete." 'Green'

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 4: READINESS VALIDATION
# ═══════════════════════════════════════════════════════════════════════════════
Write-Step "=== STEP 4: Readiness validation ===" 'Cyan'

$readinessReport = @{}
$allLabVMs = Get-VM | Where-Object { $_.Name -like "*-${ShortId}" }
foreach ($vm in $allLabVMs) {
    $hb     = $vm.Heartbeat
    $status = if ($hb -in @('OkApplicationsHealthy','OkApplicationsUnknown')) { 'Ready' } else { "NotReady ($hb)" }
    $readinessReport[$vm.Name] = @{ State=$vm.State.ToString(); Heartbeat=$hb.ToString(); Status=$status }
    Write-Step "  $($vm.Name): $status" $(if ($status -eq 'Ready') { 'Green' } else { 'Red' })
}

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 5: EXPORT CREDENTIALS
# ═══════════════════════════════════════════════════════════════════════════════
Write-Step "=== STEP 5: Exporting credentials ===" 'Cyan'

if (-not (Test-Path $SessionsPath)) { New-Item -ItemType Directory -Path $SessionsPath -Force | Out-Null }

$credManifest = @{
    SessionId   = $SessionIdStr
    LabId       = 3
    LabName     = 'SOC Analyst'
    ClassId     = $ClassId
    GeneratedAt = (Get-Date -Format 'o')
    Credentials = $sessionCredentials
    Readiness   = $readinessReport
}

$credFile = Join-Path $SessionsPath "${SessionIdStr}-credentials.json"
($credManifest | ConvertTo-Json -Depth 10) | Set-Content -Path $credFile -Encoding UTF8
icacls $credFile /inheritance:r /grant "BUILTIN\Administrators:F" 2>&1 | Out-Null
Write-Step "Credentials written to: $credFile" 'Green'

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 6: DEPLOYMENT SUMMARY
# ═══════════════════════════════════════════════════════════════════════════════
$DeployEnd  = Get-Date
$Elapsed    = $DeployEnd - $DeployStart
$labVMs     = @(Get-VM | Where-Object { $_.Name -like "*-${ShortId}" })
$totalRAMMB = ($labVMs | Measure-Object -Property MemoryStartup -Sum).Sum / 1MB
$diskUsedGB = [math]::Round(
    (Get-ChildItem -Path (Join-Path $VMBasePath $SessionIdStr) -Recurse -File -ErrorAction SilentlyContinue |
     Measure-Object -Property Length -Sum).Sum / 1GB, 2)

Write-Host ''
Write-Host ('=' * 70) -ForegroundColor Green
Write-Host "  DEPLOYMENT SUMMARY — Lab 03 SOC Analyst" -ForegroundColor Green
Write-Host ('=' * 70) -ForegroundColor Green
Write-Host "  Session ID      : $SessionIdStr"
Write-Host "  Class ID        : $ClassId"
Write-Host "  Students        : $($StudentIds.Count)"
Write-Host "  VMs Deployed    : $($labVMs.Count)"
Write-Host "  Total RAM Alloc : $([math]::Round($totalRAMMB / 1024, 1)) GB"
Write-Host "  Total Disk Used : ${diskUsedGB} GB"
Write-Host "  Time Elapsed    : $($Elapsed.ToString('hh\:mm\:ss'))"
Write-Host "  Attack Sims     : Fire 30 min after deploy (check Task Scheduler)"
Write-Host "  Credentials     : $credFile"
Write-Host "  Log             : $TranscriptFile"
Write-Host ('=' * 70) -ForegroundColor Green

Stop-Transcript
