param(
    [string]$ComposeFile = "docker-compose.yml",
    [string]$DbName = "guacamole_db",
    [string]$DbUser = "guacamole_user",
    [string]$GuacService = "guacamole",
    [string]$DbService = "postgres"
)

$ErrorActionPreference = "Stop"

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    throw "docker CLI is required."
}

Write-Host "Initializing Guacamole schema in PostgreSQL..."

# Capture SQL generated by Guacamole init script
$initSql = docker compose -f $ComposeFile exec -T $GuacService /opt/guacamole/bin/initdb.sh --postgres

if ([string]::IsNullOrWhiteSpace($initSql)) {
    throw "Guacamole init script produced no SQL output."
}

# Pipe SQL into postgres psql stdin
$initSql | docker compose -f $ComposeFile exec -T $DbService psql -U $DbUser -d $DbName

Write-Host "Guacamole schema initialization complete."
